### PR TITLE
Added flint, bowls, aspen/birch(planks, logs, leaves) and apple/oak(planks, logs)

### PR DESCRIPTION
**Pull request by Kazooo100**
Added flint, bowls, bottles, aspen/birch (logs, leaves, planks) and apple (logs, planks)

### CODE REVIEW

**Review by wsor4035 — COMMENTED** [review]
please fix your indentation

**Comment by wsor4035** [comment]
also see luacheck warnings

**Comment by Kazooo100** [comment]
Will fix the indents and remove duplicate bottle.
How do you modify/edit a pr?

**Review by wsor4035 — APPROVED** [review]
looks good

**Pull request merged**
